
# █▀▀ █░█ █▀█ █▀ █▀█ █▀█
# █▄▄ █▄█ █▀▄ ▄█ █▄█ █▀▄

exec = hyprctl setcursor McMojave-cursors 36
exec = gsettings set org.gnome.desktop.interface cursor-theme McMojave-cursors
exec = gsettings set org.gnome.desktop.interface cursor-size 36


# █▀▀ █▀█ █▄░█ ▀█▀
# █▀░ █▄█ █░▀█ ░█░

exec = gsettings set org.gnome.desktop.interface font-name 'SF Pro Text Regular 12'
exec = gsettings set org.gnome.desktop.interface document-font-name 'SF Pro Text Regular 12'
exec = gsettings set org.gnome.desktop.interface monospace-font-name 'SFMono 10'
exec = gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
exec = gsettings set org.gnome.desktop.interface font-hinting 'full'


# █▀ █▀█ █▀▀ █▀▀ █ ▄▀█ █░░
# ▄█ █▀▀ ██▄ █▄▄ █ █▀█ █▄▄

decoration {
    dim_special = 0.3
    blur {
        special = true
    }
}
