[window]
opacity = 0.8
decorations = "None"
blur = true
title = "Terminal"
dynamic_padding = true

[cursor]
style = { shape = "Beam", blinking = "Always" }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12.0

[colors.primary]
background = "#000000"
foreground = "#c0caf5"

[colors.normal]
black = "#414868"
red = "#f7768e"
green = "#73daca"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#73daca"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"
